### ISSUE TITLE
Unreal engine visualization

### ISSUE THREAD

**Issue by skelder** [audiofhrozen/motion_dance#2]
Hello,

Is there any chance for me to get the UE4 virtual environment that you used for the visualization or any tips for setting up similar environment?

Thank you.

**Comment by Fhrozen** [comment]
I think that is time about to release it.
I was planning to implement better graphics but probably it could be better if it gets released. 
Gimme a couples of hours

**Comment by Fhrozen** [comment]
I just finished the upload:
the git is https://github.com/audiofhrozen/dance-engine
You can either download the original code or a built version.
Let me know if there is any error for the execution.

**Comment by skelder** [comment]
Thank you for the quick update!

I have few questions regarding the uploaded environment.

1. Just to make sure: I believe I have to run the environment first and then the emulation code. Is there any indication of environment being ready for input or is it just ready from the get go without much noticeable delay?

2. Does the BP_Dancer folder(inside the environment project folder) contain every logic or is there any other parts that I may need to reproduce similar setup? (This question is due to my lack of knowledge on Unreal engine)

3. Is the built version of the environment waiting for input on localhost with 6060 port?

Currently when I run emulate_realtime.bat with environment running it just plays the music without actually visualizing the moves.

**Comment by Fhrozen** [comment]
>Just to make sure: I believe I have to run the environment first and then the emulation code. Is there any indication of environment being ready for input or is it just ready from the get go without much noticeable delay?

There should be a message in blue Funcion OSCReceiver aca (from spanish fuction <> here). I think that this should be displayed, but it maybe only works for develop not for deploy so it is ready at the beginning.

![2019-11-25 (2)](https://user-images.githubusercontent.com/11988996/69541414-6d512180-0fcc-11ea-9b52-16cf13b0aaaa.png)

>Does the BP_Dancer folder(inside the environment project folder) contain every logic or is there any other parts that I may need to reproduce similar setup? (This question is due to my lack of knowledge on Unreal engine)

Yes, it contains every logic. 

> Is the built version of the environment waiting for input on localhost with 6060 port?

Yes, it is setup to use port 6060. Maybe this currently a problem so I will try to fix it for custom setting.

I will try to check the code tomorrow. And fix either the built one or the code are having errors.

**Comment by skelder** [comment]
Actually I found the problem!

It turns out that if I passed the IP as numbers instead of "localhost" in the argument for ue4_net.py it would communicate with the environment without much problems!

One last question: I am wondering if I can use the trained model with a new song which was not in the training set? Or would I need to create annotations for the new song before I can throw it at the model?

**Comment by Fhrozen** [comment]
> I am wondering if I can use the trained model with a new song which was not in the training set? 

The idea is that, to test with untrained songs. Of the motion will be limited and still constrained.

>Or would I need to create annotations for the new song before I can throw it at the model?

Only if you want to train, for testing this part seems unnecessary.

**Comment by Fhrozen** [comment]
> It turns out that if I passed the IP as numbers instead of "localhost" in the argument for ue4_net.py it would communicate with the environment without much problems!

This does not works only for localhost or neither for 127.0.0.1?

**Comment by skelder** [comment]
Only localhost seems to have problems

127.0.0.1 works fine as well

**Comment by Fhrozen** [comment]
Ok, so it seems that the problem is more with python-osc rather than the engine.
I will add a conversion from localhost to 127.0.0.1 then. 
Thank you for the report
